import { createFileRoute, Link } from '@tanstack/react-router'
import { useState, useEffect } from 'react'
import {
  BookOpen, Brain, BarChart2, Timer, CheckSquare, Zap, Star,
  ArrowRight, Play, TrendingUp, Award, Users, Clock, Target,
  ChevronRight, Moon, Sun
} from 'lucide-react'
import { useTheme } from '@/routes/__root'

export const Route = createFileRoute('/')({
  component: LandingPage,
})

const features = [
  {
    icon: Brain,
    title: 'AI Study Planner',
    description: 'Get personalized study schedules generated by AI based on your subjects, deadlines, and difficulty levels.',
    color: '#6366f1',
    bg: 'rgba(99,102,241,0.1)',
  },
  {
    icon: BarChart2,
    title: 'Productivity Analytics',
    description: 'Track study hours, visualize progress, and get weekly insights to optimize your performance.',
    color: '#8b5cf6',
    bg: 'rgba(139,92,246,0.1)',
  },
  {
    icon: Timer,
    title: 'Focus Mode',
    description: 'Built-in Pomodoro timer with ambient sounds and motivational quotes to keep you in the zone.',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.1)',
  },
  {
    icon: CheckSquare,
    title: 'Task Manager',
    description: 'Organize assignments, set priorities, and track completion with a beautiful drag-and-drop interface.',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.1)',
  },
  {
    icon: Target,
    title: 'Exam Countdown',
    description: 'Never miss an exam with animated countdown timers and smart revision reminders.',
    color: '#ec4899',
    bg: 'rgba(236,72,153,0.1)',
  },
  {
    icon: Zap,
    title: 'Gamification',
    description: 'Earn XP, unlock badges, and maintain study streaks to make learning addictive and fun.',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.1)',
  },
]

const stats = [
  { value: '50K+', label: 'Active Students', icon: Users },
  { value: '2.4M+', label: 'Study Hours Tracked', icon: Clock },
  { value: '94%', label: 'Improved Grades', icon: TrendingUp },
  { value: '4.9★', label: 'Average Rating', icon: Star },
]

const testimonials = [
  {
    name: 'Sarah Chen',
    role: 'Pre-Med Student, Harvard',
    avatar: 'SC',
    text: 'Smart Study Planner AI completely transformed how I prepare for exams. My grades went from B+ to A in just one semester!',
    rating: 5,
  },
  {
    name: 'Marcus Williams',
    role: 'CS Student, MIT',
    avatar: 'MW',
    text: "The AI-generated schedules are incredibly accurate. It somehow knows exactly when I need a break and what to study next.",
    rating: 5,
  },
  {
    name: 'Priya Patel',
    role: 'Engineering Student, Stanford',
    avatar: 'PP',
    text: "The focus mode with Pomodoro timer helped me double my productive study hours. I can't imagine studying without it now.",
    rating: 5,
  },
]

function AnimatedCounter({ target, suffix = '' }: { target: number; suffix?: string }) {
  const [count, setCount] = useState(0)

  useEffect(() => {
    const step = target / 60
    let current = 0
    const timer = setInterval(() => {
      current += step
      if (current >= target) {
        setCount(target)
        clearInterval(timer)
      } else {
        setCount(Math.floor(current))
      }
    }, 16)
    return () => clearInterval(timer)
  }, [target])

  return <>{count.toLocaleString()}{suffix}</>
}

function LandingPage() {
  const { theme, toggleTheme } = useTheme()

  return (
    <div className="min-h-screen overflow-x-hidden" style={{ background: 'var(--bg-primary)' }}>
      {/* Ambient orbs */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div
          className="orb orb-primary"
          style={{ width: 600, height: 600, top: -200, left: -200 }}
        />
        <div
          className="orb orb-secondary"
          style={{ width: 500, height: 500, top: '30%', right: -200 }}
        />
        <div
          className="orb orb-pink"
          style={{ width: 400, height: 400, bottom: '10%', left: '30%' }}
        />
      </div>

      {/* Nav */}
      <nav
        className="fixed top-0 left-0 right-0 z-50 glass"
        style={{ borderBottom: '1px solid var(--glass-border)' }}
      >
        <div className="max-w-7xl mx-auto px-4 md:px-8 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2" style={{ textDecoration: 'none' }}>
            <div
              className="w-9 h-9 rounded-xl flex items-center justify-center"
              style={{ background: 'var(--gradient-primary)' }}
            >
              <BookOpen size={18} color="white" />
            </div>
            <span className="font-bold text-lg" style={{ color: 'var(--text-primary)' }}>
              StudyAI
            </span>
          </Link>
          <div className="hidden md:flex items-center gap-6 text-sm" style={{ color: 'var(--text-secondary)' }}>
            <a href="#features" style={{ color: 'inherit', textDecoration: 'none' }}>Features</a>
            <a href="#stats" style={{ color: 'inherit', textDecoration: 'none' }}>Stats</a>
            <a href="#testimonials" style={{ color: 'inherit', textDecoration: 'none' }}>Reviews</a>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={toggleTheme}
              className="p-2 rounded-lg"
              style={{ color: 'var(--text-secondary)', background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}
            >
              {theme === 'dark' ? <Sun size={16} /> : <Moon size={16} />}
            </button>
            <Link to="/login" className="btn-secondary text-sm px-4 py-2">Log In</Link>
            <Link to="/dashboard" className="btn-primary text-sm px-4 py-2">Get Started</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative pt-32 pb-20 px-4 md:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <div
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-6 text-sm font-medium animate-fade-in-up"
            style={{
              background: 'rgba(99,102,241,0.1)',
              border: '1px solid rgba(99,102,241,0.2)',
              color: '#818cf8',
            }}
          >
            <Zap size={14} />
            AI-Powered Study Platform for Students
          </div>

          <h1
            className="text-4xl md:text-7xl font-black mb-6 leading-tight animate-fade-in-up animate-delay-100"
            style={{ color: 'var(--text-primary)' }}
          >
            Study Smarter,{' '}
            <span className="gradient-text">Not Harder</span>
            <br />
            with AI
          </h1>

          <p
            className="text-lg md:text-xl mb-10 max-w-2xl mx-auto animate-fade-in-up animate-delay-200"
            style={{ color: 'var(--text-secondary)', lineHeight: 1.7 }}
          >
            Smart Study Planner AI creates personalized study schedules, tracks your progress,
            and helps you ace every exam with intelligent recommendations.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16 animate-fade-in-up animate-delay-300">
            <Link to="/dashboard" className="btn-primary text-base px-8 py-4">
              <Play size={18} />
              Start Planning Free
            </Link>
            <a href="#features" className="btn-secondary text-base px-8 py-4">
              See How It Works
              <ArrowRight size={16} />
            </a>
          </div>

          {/* Hero dashboard preview */}
          <div
            className="relative mx-auto max-w-5xl rounded-2xl overflow-hidden animate-fade-in-up animate-delay-400"
            style={{
              background: 'var(--bg-card)',
              border: '1px solid var(--border-color)',
              boxShadow: '0 40px 100px rgba(0,0,0,0.5), 0 0 0 1px rgba(99,102,241,0.1)',
            }}
          >
            {/* Mock dashboard UI */}
            <div
              className="flex items-center gap-2 px-4 py-3 border-b"
              style={{ borderColor: 'var(--border-color)', background: 'rgba(0,0,0,0.2)' }}
            >
              <div className="w-3 h-3 rounded-full" style={{ background: '#ef4444' }} />
              <div className="w-3 h-3 rounded-full" style={{ background: '#f59e0b' }} />
              <div className="w-3 h-3 rounded-full" style={{ background: '#10b981' }} />
              <div
                className="flex-1 text-center text-xs rounded"
                style={{ color: 'var(--text-muted)', background: 'rgba(255,255,255,0.05)', padding: '2px 12px' }}
              >
                studyai.app/dashboard
              </div>
            </div>
            <div className="p-6 grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                { label: 'Today\'s Study Time', value: '3h 45m', change: '+12%', color: '#6366f1' },
                { label: 'Tasks Completed', value: '8/12', change: 'On track', color: '#10b981' },
                { label: 'Exam in', value: '8 Days', change: 'Math Final', color: '#ec4899' },
              ].map((card) => (
                <div
                  key={card.label}
                  className="p-4 rounded-xl"
                  style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.06)' }}
                >
                  <div className="text-xs mb-2" style={{ color: 'var(--text-muted)' }}>{card.label}</div>
                  <div className="text-2xl font-bold mb-1" style={{ color: card.color }}>{card.value}</div>
                  <div
                    className="text-xs px-2 py-0.5 rounded-full inline-flex"
                    style={{ background: `${card.color}20`, color: card.color }}
                  >
                    {card.change}
                  </div>
                </div>
              ))}
            </div>
            <div className="px-6 pb-6 grid grid-cols-1 md:grid-cols-2 gap-4">
              <div
                className="p-4 rounded-xl"
                style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.06)' }}
              >
                <div className="text-xs font-semibold mb-3" style={{ color: 'var(--text-secondary)' }}>
                  Today's AI Schedule
                </div>
                {[
                  { time: '9:00 AM', subject: 'Mathematics', duration: '90 min', color: '#6366f1' },
                  { time: '11:00 AM', subject: 'Physics Review', duration: '60 min', color: '#8b5cf6' },
                  { time: '2:00 PM', subject: 'Chemistry Lab', duration: '45 min', color: '#06b6d4' },
                ].map((item) => (
                  <div key={item.time} className="flex items-center gap-3 mb-2">
                    <div className="text-xs w-16" style={{ color: 'var(--text-muted)' }}>{item.time}</div>
                    <div className="w-2 h-2 rounded-full" style={{ background: item.color }} />
                    <div className="flex-1 text-xs" style={{ color: 'var(--text-primary)' }}>{item.subject}</div>
                    <div className="text-xs" style={{ color: 'var(--text-muted)' }}>{item.duration}</div>
                  </div>
                ))}
              </div>
              <div
                className="p-4 rounded-xl"
                style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.06)' }}
              >
                <div className="text-xs font-semibold mb-3" style={{ color: 'var(--text-secondary)' }}>
                  Weekly Progress
                </div>
                <div className="flex items-end gap-2 h-16">
                  {[60, 85, 45, 90, 70, 95, 80].map((h, i) => (
                    <div
                      key={i}
                      className="flex-1 rounded-sm"
                      style={{
                        height: `${h}%`,
                        background: i === 6
                          ? 'var(--gradient-primary)'
                          : 'rgba(99,102,241,0.2)',
                      }}
                    />
                  ))}
                </div>
                <div className="flex justify-between mt-1">
                  {['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => (
                    <div key={i} className="flex-1 text-center text-xs" style={{ color: 'var(--text-muted)' }}>{d}</div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section id="stats" className="py-20 px-4 md:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {stats.map(({ value, label, icon: Icon }) => (
              <div
                key={label}
                className="text-center p-6 rounded-2xl card-hover"
                style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}
              >
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center mx-auto mb-4"
                  style={{ background: 'rgba(99,102,241,0.1)' }}
                >
                  <Icon size={24} style={{ color: '#818cf8' }} />
                </div>
                <div className="text-3xl font-black mb-1 gradient-text">{value}</div>
                <div className="text-sm" style={{ color: 'var(--text-secondary)' }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-4 md:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <div
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-4 text-sm font-medium"
              style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.2)', color: '#818cf8' }}
            >
              Everything You Need
            </div>
            <h2
              className="text-3xl md:text-5xl font-black mb-4"
              style={{ color: 'var(--text-primary)' }}
            >
              Powerful Features for{' '}
              <span className="gradient-text">Peak Performance</span>
            </h2>
            <p className="text-lg max-w-2xl mx-auto" style={{ color: 'var(--text-secondary)' }}>
              Every tool you need to study smarter, achieve more, and stress less.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map(({ icon: Icon, title, description, color, bg }) => (
              <div
                key={title}
                className="p-6 rounded-2xl card-hover cursor-pointer"
                style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}
              >
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center mb-4"
                  style={{ background: bg }}
                >
                  <Icon size={24} style={{ color }} />
                </div>
                <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--text-primary)' }}>{title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{description}</p>
                <div className="flex items-center gap-1 mt-4 text-sm font-medium" style={{ color }}>
                  Learn more <ChevronRight size={14} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="py-20 px-4 md:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2
              className="text-3xl md:text-5xl font-black mb-4"
              style={{ color: 'var(--text-primary)' }}
            >
              Loved by{' '}
              <span className="gradient-text-pink">50,000+ Students</span>
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map(({ name, role, avatar, text, rating }) => (
              <div
                key={name}
                className="p-6 rounded-2xl card-hover"
                style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}
              >
                <div className="flex gap-1 mb-4">
                  {Array.from({ length: rating }).map((_, i) => (
                    <Star key={i} size={14} fill="#f59e0b" style={{ color: '#f59e0b' }} />
                  ))}
                </div>
                <p className="text-sm leading-relaxed mb-6" style={{ color: 'var(--text-secondary)' }}>
                  "{text}"
                </p>
                <div className="flex items-center gap-3">
                  <div
                    className="w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold"
                    style={{ background: 'var(--gradient-primary)' }}
                  >
                    {avatar}
                  </div>
                  <div>
                    <div className="font-semibold text-sm" style={{ color: 'var(--text-primary)' }}>{name}</div>
                    <div className="text-xs" style={{ color: 'var(--text-muted)' }}>{role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-4 md:px-8">
        <div className="max-w-3xl mx-auto text-center">
          <div
            className="p-12 rounded-3xl"
            style={{
              background: 'linear-gradient(135deg, rgba(99,102,241,0.15), rgba(139,92,246,0.1))',
              border: '1px solid rgba(99,102,241,0.2)',
            }}
          >
            <h2
              className="text-3xl md:text-5xl font-black mb-4"
              style={{ color: 'var(--text-primary)' }}
            >
              Ready to Transform Your{' '}
              <span className="gradient-text">Study Game?</span>
            </h2>
            <p className="text-lg mb-8" style={{ color: 'var(--text-secondary)' }}>
              Join 50,000+ students already using StudyAI to ace their exams.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link to="/dashboard" className="btn-primary text-base px-10 py-4">
                <Zap size={18} />
                Start for Free
              </Link>
              <Link to="/login" className="btn-secondary text-base px-8 py-4">
                Sign In
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer
        className="border-t py-12 px-4 md:px-8"
        style={{ borderColor: 'var(--border-color)' }}
      >
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center gap-2 mb-3">
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center"
                  style={{ background: 'var(--gradient-primary)' }}
                >
                  <BookOpen size={16} color="white" />
                </div>
                <span className="font-bold" style={{ color: 'var(--text-primary)' }}>StudyAI</span>
              </div>
              <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
                AI-powered study platform helping students achieve their academic goals.
              </p>
            </div>
            {[
              { title: 'Product', links: ['Features', 'Dashboard', 'Analytics', 'Focus Mode'] },
              { title: 'Resources', links: ['Blog', 'Study Tips', 'Community', 'Support'] },
              { title: 'Company', links: ['About', 'Privacy', 'Terms', 'Contact'] },
            ].map(({ title, links }) => (
              <div key={title}>
                <h4 className="font-semibold text-sm mb-3" style={{ color: 'var(--text-primary)' }}>{title}</h4>
                <ul className="space-y-2">
                  {links.map((link) => (
                    <li key={link}>
                      <a href="#" className="text-sm" style={{ color: 'var(--text-muted)', textDecoration: 'none' }}>
                        {link}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <div
            className="border-t pt-6 flex flex-col md:flex-row items-center justify-between gap-4"
            style={{ borderColor: 'var(--border-color)' }}
          >
            <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
              © 2026 Smart Study Planner AI. All rights reserved.
            </p>
            <div className="flex gap-1">
              {Array.from({ length: 5 }).map((_, i) => (
                <Star key={i} size={12} fill="#f59e0b" style={{ color: '#f59e0b' }} />
              ))}
              <span className="text-xs ml-1" style={{ color: 'var(--text-muted)' }}>4.9/5 from 12,000 reviews</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
